import Foundation

// MARK: - Request / Response models (not generated by Tapper)

struct LoginRequest: Encodable {
    let username: String
    let password: String
}

struct RegisterRequest: Encodable {
    let username: String
    let email: String
    let password: String
}

struct AnonymousRegisterRequest: Encodable {
    let playerId: String
    let displayName: String
}

struct AuthResponse: Decodable {
    let success: Bool
    let token: String?
    let error: String?
    let user: AuthUser?
}

struct AuthUser: Decodable {
    let userId: String
    let username: String
    let displayName: String
}

// MARK: - AuthService

@MainActor
final class AuthService: ObservableObject {
    static let shared = AuthService()

    @Published var currentUser: AuthUser?
    @Published var token: String?

    private let tokenKey = "auth_token"
    private let userKey = "auth_user"

    private init() {
        restoreFromDefaults()
    }

    // MARK: - Public API

    func login(username: String, password: String) async throws {
        let body = LoginRequest(username: username, password: password)
        let response: AuthResponse = try await post("/api/auth/login", body: body)
        guard response.success, let tok = response.token, let user = response.user else {
            throw AuthError.serverError(response.error ?? "Login failed")
        }
        persist(token: tok, user: user)
    }

    func register(username: String, email: String, password: String) async throws {
        let body = RegisterRequest(username: username, email: email, password: password)
        let response: AuthResponse = try await post("/api/auth/register", body: body)
        guard response.success, let tok = response.token, let user = response.user else {
            throw AuthError.serverError(response.error ?? "Registration failed")
        }
        persist(token: tok, user: user)
    }

    func registerAnonymous() async throws {
        let playerId = getOrCreatePlayerId()
        let displayName = "Anon-\(playerId.suffix(6))"
        let body = AnonymousRegisterRequest(playerId: playerId, displayName: displayName)
        let response: AuthResponse = try await post("/api/auth/register-anonymous", body: body)
        guard response.success, let tok = response.token, let user = response.user else { return }
        persist(token: tok, user: user)
    }

    func restoreSession() async {
        guard let tok = token else {
            try? await registerAnonymous()
            return
        }
        // Validate token is still good
        do {
            let _: AuthUser = try await get("/api/auth/me", token: tok)
        } catch {
            logout()
            try? await registerAnonymous()
        }
    }

    func logout() {
        token = nil
        currentUser = nil
        UserDefaults.standard.removeObject(forKey: tokenKey)
        UserDefaults.standard.removeObject(forKey: userKey)
    }

    // MARK: - Private

    private func persist(token tok: String, user: AuthUser) {
        self.token = tok
        self.currentUser = user
        UserDefaults.standard.set(tok, forKey: tokenKey)
        if let data = try? JSONEncoder().encode(user) {
            UserDefaults.standard.set(data, forKey: userKey)
        }
    }

    private func restoreFromDefaults() {
        token = UserDefaults.standard.string(forKey: tokenKey)
        if let data = UserDefaults.standard.data(forKey: userKey) {
            currentUser = try? JSONDecoder().decode(AuthUser.self, from: data)
        }
    }

    private func getOrCreatePlayerId() -> String {
        let key = "anonymous_player_id"
        if let existing = UserDefaults.standard.string(forKey: key) { return existing }
        let new = "player_\(Int(Date().timeIntervalSince1970))_\(UUID().uuidString.prefix(8))"
        UserDefaults.standard.set(new, forKey: key)
        return new
    }

    // MARK: - HTTP helpers

    private func post<Body: Encodable, Response: Decodable>(_ path: String, body: Body) async throws -> Response {
        var request = URLRequest(url: URL(string: Config.serverURL + path)!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        if let tok = token {
            request.setValue("Bearer \(tok)", forHTTPHeaderField: "Authorization")
        }
        request.httpBody = try JSONEncoder().encode(body)
        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(Response.self, from: data)
    }

    private func get<Response: Decodable>(_ path: String, token tok: String) async throws -> Response {
        var request = URLRequest(url: URL(string: Config.serverURL + path)!)
        request.setValue("Bearer \(tok)", forHTTPHeaderField: "Authorization")
        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
            throw AuthError.unauthorized
        }
        return try JSONDecoder().decode(Response.self, from: data)
    }
}

enum AuthError: LocalizedError {
    case unauthorized
    case serverError(String)

    var errorDescription: String? {
        switch self {
        case .unauthorized: return "Session expired. Please log in again."
        case .serverError(let msg): return msg
        }
    }
}
