// <auto-generated />
using System;
using Backgammon.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backgammon.Server.Data.Migrations;
    [DbContext(typeof(BackgammonDbContext))]
    [Migration("20260524181930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backgammon.Server.Models.BoardTheme", b =>
                {
                    b.Property<string>("ThemeId")
                        .HasColumnType("text")
                        .HasColumnName("theme_id")
                        .HasJsonPropertyName("themeId");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id")
                        .HasJsonPropertyName("authorId");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_username")
                        .HasJsonPropertyName("authorUsername");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("colors")
                        .HasJsonPropertyName("colors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default")
                        .HasJsonPropertyName("isDefault");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count")
                        .HasJsonPropertyName("likeCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url")
                        .HasJsonPropertyName("thumbnailUrl");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count")
                        .HasJsonPropertyName("usageCount");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility")
                        .HasJsonPropertyName("visibility");

                    b.HasKey("ThemeId");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_board_themes_author_id");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_board_themes_is_default");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_board_themes_visibility");

                    b.ToTable("board_themes", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.DailyPuzzle", b =>
                {
                    b.Property<string>("PuzzleId")
                        .HasColumnType("text")
                        .HasColumnName("puzzle_id")
                        .HasJsonPropertyName("puzzleId");

                    b.Property<string>("AlternativeMoves")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alternative_moves")
                        .HasJsonPropertyName("alternativeMoves");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count")
                        .HasJsonPropertyName("attemptCount");

                    b.Property<double>("BestMoveEquity")
                        .HasColumnType("double precision")
                        .HasColumnName("best_move_equity")
                        .HasJsonPropertyName("bestMoveEquity");

                    b.Property<string>("BestMoves")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("best_moves")
                        .HasJsonPropertyName("bestMoves");

                    b.Property<string>("BestMovesNotation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("best_moves_notation")
                        .HasJsonPropertyName("bestMovesNotation");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_state")
                        .HasJsonPropertyName("boardState");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("CurrentPlayer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("current_player")
                        .HasJsonPropertyName("currentPlayer");

                    b.Property<string>("Dice")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dice")
                        .HasJsonPropertyName("dice");

                    b.Property<string>("EvaluatorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("evaluator_type")
                        .HasJsonPropertyName("evaluatorType");

                    b.Property<string>("PositionSgf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_sgf")
                        .HasJsonPropertyName("positionSgf");

                    b.Property<string>("PuzzleDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("puzzle_date")
                        .HasJsonPropertyName("puzzleDate");

                    b.Property<int>("RedBornOff")
                        .HasColumnType("integer")
                        .HasColumnName("red_born_off")
                        .HasJsonPropertyName("redBornOff");

                    b.Property<int>("RedCheckersOnBar")
                        .HasColumnType("integer")
                        .HasColumnName("red_checkers_on_bar")
                        .HasJsonPropertyName("redCheckersOnBar");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer")
                        .HasColumnName("solved_count")
                        .HasJsonPropertyName("solvedCount");

                    b.Property<int>("WhiteBornOff")
                        .HasColumnType("integer")
                        .HasColumnName("white_born_off")
                        .HasJsonPropertyName("whiteBornOff");

                    b.Property<int>("WhiteCheckersOnBar")
                        .HasColumnType("integer")
                        .HasColumnName("white_checkers_on_bar")
                        .HasJsonPropertyName("whiteCheckersOnBar");

                    b.HasKey("PuzzleId");

                    b.HasIndex("PuzzleDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_puzzles_date");

                    b.ToTable("daily_puzzles", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.Friendship", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.Property<string>("FriendUserId")
                        .HasColumnType("text")
                        .HasColumnName("friend_user_id")
                        .HasJsonPropertyName("friendUserId");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasJsonPropertyName("acceptedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("FriendDisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("friend_display_name")
                        .HasJsonPropertyName("friendDisplayName");

                    b.Property<string>("FriendUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("friend_username")
                        .HasJsonPropertyName("friendUsername");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initiated_by")
                        .HasJsonPropertyName("initiatedBy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasJsonPropertyName("status");

                    b.HasKey("UserId", "FriendUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_friendships_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_friendships_user_status");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("text")
                        .HasColumnName("game_id");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_state")
                        .HasJsonPropertyName("boardState");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at")
                        .HasJsonPropertyName("completedAt");

                    b.Property<string>("CoreGame")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("core_game")
                        .HasJsonPropertyName("coreGame");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("CurrentPlayer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_player")
                        .HasJsonPropertyName("currentPlayer");

                    b.Property<int>("Die1")
                        .HasColumnType("integer")
                        .HasColumnName("die1")
                        .HasJsonPropertyName("die1");

                    b.Property<int>("Die2")
                        .HasColumnType("integer")
                        .HasColumnName("die2")
                        .HasJsonPropertyName("die2");

                    b.Property<string>("DoublingCubeOwner")
                        .HasColumnType("text")
                        .HasColumnName("doubling_cube_owner")
                        .HasJsonPropertyName("doublingCubeOwner");

                    b.Property<int>("DoublingCubeValue")
                        .HasColumnType("integer")
                        .HasColumnName("doubling_cube_value")
                        .HasJsonPropertyName("doublingCubeValue");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds")
                        .HasJsonPropertyName("durationSeconds");

                    b.Property<bool>("GameStarted")
                        .HasColumnType("boolean")
                        .HasColumnName("game_started")
                        .HasJsonPropertyName("gameStarted");

                    b.Property<bool>("IsAiOpponent")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isAiOpponent");

                    b.Property<bool>("IsRated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rated")
                        .HasJsonPropertyName("isRated");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasJsonPropertyName("lastUpdatedAt");

                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer")
                        .HasColumnName("move_count")
                        .HasJsonPropertyName("moveCount");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("moves")
                        .HasJsonPropertyName("moves");

                    b.Property<int>("RedBornOff")
                        .HasColumnType("integer")
                        .HasColumnName("red_born_off")
                        .HasJsonPropertyName("redBornOff");

                    b.Property<int>("RedCheckersOnBar")
                        .HasColumnType("integer")
                        .HasColumnName("red_checkers_on_bar")
                        .HasJsonPropertyName("redCheckersOnBar");

                    b.Property<string>("RedPlayerId")
                        .HasColumnType("text")
                        .HasColumnName("red_player_id")
                        .HasJsonPropertyName("redPlayerId");

                    b.Property<string>("RedPlayerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("red_player_name")
                        .HasJsonPropertyName("redPlayerName");

                    b.Property<int?>("RedRatingAfter")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("redRatingAfter");

                    b.Property<int?>("RedRatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("red_rating_before")
                        .HasJsonPropertyName("redRatingBefore");

                    b.Property<string>("RedUserId")
                        .HasColumnType("text")
                        .HasColumnName("red_user_id")
                        .HasJsonPropertyName("redUserId");

                    b.Property<string>("RemainingMoves")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("remaining_moves")
                        .HasJsonPropertyName("remainingMoves");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Turns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("turns")
                        .HasJsonPropertyName("turns");

                    b.Property<int>("WhiteBornOff")
                        .HasColumnType("integer")
                        .HasColumnName("white_born_off")
                        .HasJsonPropertyName("whiteBornOff");

                    b.Property<int>("WhiteCheckersOnBar")
                        .HasColumnType("integer")
                        .HasColumnName("white_checkers_on_bar")
                        .HasJsonPropertyName("whiteCheckersOnBar");

                    b.Property<string>("WhitePlayerId")
                        .HasColumnType("text")
                        .HasColumnName("white_player_id")
                        .HasJsonPropertyName("whitePlayerId");

                    b.Property<string>("WhitePlayerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("white_player_name")
                        .HasJsonPropertyName("whitePlayerName");

                    b.Property<int?>("WhiteRatingAfter")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("whiteRatingAfter");

                    b.Property<int?>("WhiteRatingBefore")
                        .HasColumnType("integer")
                        .HasColumnName("white_rating_before")
                        .HasJsonPropertyName("whiteRatingBefore");

                    b.Property<string>("WhiteUserId")
                        .HasColumnType("text")
                        .HasColumnName("white_user_id")
                        .HasJsonPropertyName("whiteUserId");

                    b.HasKey("GameId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_games_created_at");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_games_match_id");

                    b.HasIndex("RedUserId")
                        .HasDatabaseName("ix_games_red_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_games_status");

                    b.HasIndex("WhiteUserId")
                        .HasDatabaseName("ix_games_white_user_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.Match", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoreMatch")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("core_match")
                        .HasJsonPropertyName("coreMatch");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentGameId")
                        .HasColumnType("text")
                        .HasColumnName("current_game_id");

                    b.Property<string>("CurrentTurnPlayerId")
                        .HasColumnType("text")
                        .HasColumnName("current_turn_player_id")
                        .HasJsonPropertyName("currentTurnPlayerId");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds")
                        .HasJsonPropertyName("durationSeconds");

                    b.Property<string>("GameIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("game_ids");

                    b.Property<string>("GamesSummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("games_summary")
                        .HasJsonPropertyName("gamesSummary");

                    b.Property<bool>("HasCrawfordGameBeenPlayed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCorrespondence")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correspondence")
                        .HasJsonPropertyName("isCorrespondence");

                    b.Property<bool>("IsCrawfordGame")
                        .HasColumnType("boolean")
                        .HasColumnName("is_crawford_game");

                    b.Property<bool>("IsOpenLobby")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open_lobby")
                        .HasJsonPropertyName("isOpenLobby");

                    b.Property<bool>("IsRated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rated")
                        .HasJsonPropertyName("isRated");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasJsonPropertyName("lastUpdatedAt");

                    b.Property<string>("LobbyStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lobby_status")
                        .HasJsonPropertyName("lobbyStatus");

                    b.Property<string>("OpponentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("opponent_type")
                        .HasJsonPropertyName("opponentType");

                    b.Property<string>("Player1DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player1_display_name")
                        .HasJsonPropertyName("player1DisplayName");

                    b.Property<string>("Player1Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player1_id");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player1_name")
                        .HasJsonPropertyName("player1Name");

                    b.Property<int>("Player1Score")
                        .HasColumnType("integer")
                        .HasColumnName("player1_score");

                    b.Property<string>("Player2DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player2_display_name")
                        .HasJsonPropertyName("player2DisplayName");

                    b.Property<string>("Player2Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player2_id");

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("player2_name")
                        .HasJsonPropertyName("player2Name");

                    b.Property<int>("Player2Score")
                        .HasColumnType("integer")
                        .HasColumnName("player2_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetScore")
                        .HasColumnType("integer")
                        .HasColumnName("target_score");

                    b.Property<int>("TimePerMoveDays")
                        .HasColumnType("integer")
                        .HasColumnName("time_per_move_days")
                        .HasJsonPropertyName("timePerMoveDays");

                    b.Property<DateTime?>("TurnDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turn_deadline")
                        .HasJsonPropertyName("turnDeadline");

                    b.Property<string>("WinnerId")
                        .HasColumnType("text")
                        .HasColumnName("winner_id")
                        .HasJsonPropertyName("winnerId");

                    b.HasKey("MatchId");

                    b.HasIndex("CurrentTurnPlayerId")
                        .HasDatabaseName("ix_matches_current_turn_player");

                    b.HasIndex("IsOpenLobby")
                        .HasDatabaseName("ix_matches_is_open_lobby");

                    b.HasIndex("LastUpdatedAt")
                        .HasDatabaseName("ix_matches_last_updated_at");

                    b.HasIndex("LobbyStatus")
                        .HasDatabaseName("ix_matches_lobby_status");

                    b.HasIndex("Player1Id")
                        .HasDatabaseName("ix_matches_player1_id");

                    b.HasIndex("Player2Id")
                        .HasDatabaseName("ix_matches_player2_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_matches_status");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.PuzzleAttempt", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.Property<string>("PuzzleDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("puzzle_date")
                        .HasJsonPropertyName("puzzleDate");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count")
                        .HasJsonPropertyName("attemptCount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<double>("EquityLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("equity_loss")
                        .HasJsonPropertyName("equityLoss");

                    b.Property<bool>("GaveUp")
                        .HasColumnType("boolean")
                        .HasColumnName("gave_up")
                        .HasJsonPropertyName("gaveUp");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct")
                        .HasJsonPropertyName("isCorrect");

                    b.Property<string>("PuzzleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puzzle_id")
                        .HasJsonPropertyName("puzzleId");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at")
                        .HasJsonPropertyName("solvedAt");

                    b.Property<string>("SubmittedMoves")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("submitted_moves")
                        .HasJsonPropertyName("submittedMoves");

                    b.Property<string>("SubmittedNotation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_notation")
                        .HasJsonPropertyName("submittedNotation");

                    b.HasKey("UserId", "PuzzleDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_puzzle_attempts_user_id");

                    b.ToTable("puzzle_attempts", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.PuzzleStreakInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_streak")
                        .HasJsonPropertyName("bestStreak");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak")
                        .HasJsonPropertyName("currentStreak");

                    b.Property<string>("LastSolvedDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("last_solved_date")
                        .HasJsonPropertyName("lastSolvedDate");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts")
                        .HasJsonPropertyName("totalAttempts");

                    b.Property<int>("TotalSolved")
                        .HasColumnType("integer")
                        .HasColumnName("total_solved")
                        .HasJsonPropertyName("totalSolved");

                    b.HasKey("UserId");

                    b.ToTable("puzzle_streaks", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.RatingHistoryEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasJsonPropertyName("timestamp");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_id")
                        .HasJsonPropertyName("gameId");

                    b.Property<string>("OpponentUserId")
                        .HasColumnType("text")
                        .HasColumnName("opponent_user_id")
                        .HasJsonPropertyName("opponentUserId");

                    b.Property<string>("OpponentUsername")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("opponent_username")
                        .HasJsonPropertyName("opponentUsername");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating")
                        .HasJsonPropertyName("rating");

                    b.Property<int>("RatingChange")
                        .HasColumnType("integer")
                        .HasColumnName("rating_change")
                        .HasJsonPropertyName("ratingChange");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean")
                        .HasColumnName("won")
                        .HasJsonPropertyName("won");

                    b.HasKey("UserId", "Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rating_history_user_id");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_rating_history_user_time");

                    b.ToTable("rating_history", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.ThemeLike", b =>
                {
                    b.Property<string>("ThemeId")
                        .HasColumnType("text")
                        .HasColumnName("theme_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ThemeId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_theme_likes_user_id");

                    b.ToTable("theme_likes", (string)null);
                });

            modelBuilder.Entity("Backgammon.Server.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasJsonPropertyName("userId");

                    b.Property<string>("BannedReason")
                        .HasColumnType("text")
                        .HasColumnName("banned_reason")
                        .HasJsonPropertyName("bannedReason");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_until")
                        .HasJsonPropertyName("bannedUntil");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasJsonPropertyName("email");

                    b.Property<string>("EmailNormalized")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_normalized")
                        .HasJsonPropertyName("emailNormalized");

                    b.Property<string>("FriendsListPrivacy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("friends_list_privacy")
                        .HasJsonPropertyName("friendsListPrivacy");

                    b.Property<string>("GameHistoryPrivacy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_history_privacy")
                        .HasJsonPropertyName("gameHistoryPrivacy");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasJsonPropertyName("isActive");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous")
                        .HasJsonPropertyName("isAnonymous");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned")
                        .HasJsonPropertyName("isBanned");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasJsonPropertyName("lastLoginAt");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasJsonPropertyName("lastSeenAt");

                    b.Property<string>("LinkedAnonymousIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("linked_anonymous_ids")
                        .HasJsonPropertyName("linkedAnonymousIds");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasJsonPropertyName("passwordHash");

                    b.Property<int>("PeakRating")
                        .HasColumnType("integer")
                        .HasColumnName("peak_rating")
                        .HasJsonPropertyName("peakRating");

                    b.Property<string>("ProfilePrivacy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_privacy")
                        .HasJsonPropertyName("profilePrivacy");

                    b.Property<int>("RatedGamesCount")
                        .HasColumnType("integer")
                        .HasColumnName("rated_games_count")
                        .HasJsonPropertyName("ratedGamesCount");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating")
                        .HasJsonPropertyName("rating");

                    b.Property<DateTime?>("RatingLastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rating_last_updated_at")
                        .HasJsonPropertyName("ratingLastUpdatedAt");

                    b.Property<string>("SelectedThemeId")
                        .HasColumnType("text")
                        .HasColumnName("selected_theme_id")
                        .HasJsonPropertyName("selectedThemeId");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats")
                        .HasJsonPropertyName("stats");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username")
                        .HasJsonPropertyName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username_normalized")
                        .HasJsonPropertyName("usernameNormalized");

                    b.HasKey("UserId");

                    b.HasIndex("EmailNormalized")
                        .HasDatabaseName("ix_users_email_normalized");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_users_rating");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_users_username_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Username"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Username"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username_normalized");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
