// Types for the Players page
// These will be auto-generated by Tapper when the build runs

export interface LeaderboardEntryDto {
  rank: number
  userId: string
  username: string
  displayName: string
  rating: number
  totalGames: number
  wins: number
  losses: number
  winRate: number
  isOnline: boolean
}

export interface RatingDistributionDto {
  buckets: RatingBucketDto[]
  userRating?: number
  userPercentile?: number
  totalPlayers: number
  averageRating: number
  medianRating: number
}

export interface RatingBucketDto {
  minRating: number
  maxRating: number
  label: string
  count: number
  percentage: number
  isUserBucket: boolean
}

export interface OnlinePlayerDto {
  userId: string
  username: string
  displayName: string
  rating: number
  status: OnlinePlayerStatus
  currentGameId?: string
  isFriend: boolean
}

export enum OnlinePlayerStatus {
  Available = 0,
  InGame = 1,
  LookingForMatch = 2
}

export interface BotInfoDto {
  id: string
  name: string
  description: string
  difficulty: number
  isAvailable: boolean
  icon: string
}
